# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\ExternalWeatherApiController:
        arguments:
            $cache: '@cache.app'
            $httpClient: '@http_client'
            $serializer: '@serializer'
            
parameters:
    openweathermap_api_key: '%env(OPENWEATHER_API_KEY)%'
